### ISSUE TITLE
Unable to adjust the width of the code editor screen

### ISSUE THREAD

**Issue by aastha51551** [JdeRobot/bt-studio#205] opened 2024-10-18 11:24 UTC
The code editor screen's width can't be increased and is fixed at a particular width. Scrolling horizontally isn't quite user-friendly.

**Comment by OscarMrZ** [comment] 2024-10-19 11:22
Hi! Could you send a video of this behavior? I'm unable to reproduce

**Comment by aastha51551** [comment] 2024-10-22 08:58
![Screenshot 2024-10-18 165413](https://github.com/user-attachments/assets/5541b305-9a92-4fa3-8962-e95272ae7045)
![Screenshot 2024-10-18 164733](https://github.com/user-attachments/assets/cd2fc0c5-bb0a-4088-94e3-021312aac91b)
We aren't able to adjust the width of code viewer/editor as shown in these images

**Comment by aastha51551** [comment] 2024-10-22 09:02
Can you assign this issue to me? I would like to work on this.

**Comment by jmplaza** [comment] 2024-10-22 14:07
Hi @aastha51551 , no need of explicit assignment. Just work on the solution to this issue and submit your PR. The sooner you submit your PR the more the chances to get merged in the main branch :-)

Have you tried the brand new BT-Studio release (0.7)? Work on the issue using that release as base. 

Cheers!

**Closed** 2024-12-18 16:52 UTC
